services:
  - name: fleet
    plan: free
    type: web
    runtime: image
    image:
      url: 'fleetdm/fleet:latest'
    startCommand: "fleet prepare --no-prompt=true db && fleet serve"
    healthCheckPath: /healthz
    envVars:
      - key: FLEET_SOFTWARE_INSTALLER_STORE_DIR
        value: '/opt/fleet/installers'
      - key: FLEET_SERVER_PRIVATE_KEY
        generateValue: true
      - key: FLEET_MYSQL_ADDRESS
        fromService:
          name: fleet-mysql
          property: host
      - key: FLEET_MYSQL_PORT
        value: 3306
      - key: FLEET_MYSQL_DATABASE
        fromService:
          name: fleet-mysql
          envVarKey: MYSQL_DATABASE
      - key: FLEET_MYSQL_PASSWORD
        fromService:
          name: fleet-mysql
          envVarKey: MYSQL_PASSWORD
      - key: FLEET_MYSQL_USERNAME
        fromService:
          name: fleet-mysql
          envVarKey: MYSQL_USER
      - key: FLEET_REDIS_ADDRESS
        fromService:
          name: fleet-redis
          property: connectionString
      - key: FLEET_SERVER_TLS
        value: 'false'
      - key: PORT
        value: 8080

  - name: fleet-mysql
    plan: free
    type: web
    runtime: docker
    repo: https://github.com/kc9wwh/fleet-render-demo
    envVars:
      - key: MYSQL_DATABASE
        value: "fleetdb"
      - key: MYSQL_PASSWORD
        generateValue: true
      - key: MYSQL_ROOT_PASSWORD
        generateValue: true
      - key: MYSQL_USER
        value: "fleet"

  - name: fleet-redis
    plan: free
    type: redis
    maxmemoryPolicy: allkeys-lru
    ipAllowList: []
